### ISSUE TITLE
Unable to convert the arabic content inside the pdf file

### ISSUE THREAD

**Issue by ShyamBasa** [ArtifexSoftware/pdf2docx#320] opened 2024-10-12 08:35 UTC
### Description of the bug

I am using below code to convert the arabic pdf file to docx, but there is an issue with the conversion of arabic characters 

It converted like below:
Eg : pÍ m¿ÀÖ m¿ÌÑ m¿ÛÍ mÈ×ّ¾ m¿Ø~Ø m£¹ × ÓØ mÝ m¿mu1 

####
from pdf2docx import Converter
import os

# # # dir_path for input reading and output files & a for loop # # #

path_input = 'C:\\Users\\securetech\\Downloads\\arabic.pdf'
path_output = 'C:\\Users\\securetech\\Downloads\\arabic.docx'

cv = Converter(path_input)
cv.convert(path_output, start=0, end=None)
cv.close()
	
	

### pdf2docx version

0.5.8

### Operating system

Windows

### Python version

3.10

**Comment by green0317** [comment] 2024-10-12 10:01
Hi @ShyamBasa , Please share sample file to reproduce.

**Comment by ShyamBasa** [comment] 2024-10-14 05:54
[arabic.pdf](https://github.com/user-attachments/files/17359677/arabic.pdf)
Here is the sample file

**Comment by JorjMcKie** [comment] 2024-10-14 12:24
Thanks for the sample file. It is unusable unfortunately because the Arabian font is not extractable: it delivers &#xfffd; characters only.

**Comment by JorjMcKie** [comment] 2024-10-14 16:54
BTW - have you read the PyPI entry of hte package? It clearly states there that **_only left-to-write_** languages are currently supported:

![image](https://github.com/user-attachments/assets/8c657576-066b-49e2-bda0-2a358ec594e3)

While we may lift this restriction at some time, this is still the current status.
So I am afraid we have to close this issue for now.

**Closed by JorjMcKie** 2024-10-14 16:54 UTC
Labels: wontfix

**Comment by ShyamBasa** [comment] 2024-10-14 16:56
Thanks for the update, you can close this for now
